AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Prefix:
    Type: String
    Description: Prefix for naming resources
  Env:
    Type: String
    Description: Environment (e.g.2, dev, prod)
  Role:
    Type: String
    Description: IAM role resources

Resources:
  # ECS Cluster (Fargate)
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${Prefix}-${Env}-ecs-cluster'
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1

  # S3 Bucket for storing source code as ZIP file
  SourceCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${Prefix}-${Env}-backend-source'

  # ECS Task Definition
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Prefix}-${Env}-backend-task'
      ExecutionRoleArn: !Ref Role
      TaskRoleArn: !Ref Role
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: backend-container
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Prefix}-${Env}-backend-service:latest'
          PortMappings:
            - ContainerPort: 3000
          Environment:
            - Name: DB_HOST
              Value: !Sub test-${Env}
            - Name: DB_DATABASE
              Value: !Sub test-${Env}
            - Name: DB_PASSWORD
              Value: !Sub test-${Env}
            - Name: DB_USER
              Value: !Sub test-${Env}
            - Name: REDIS_HOST
              Value: !Sub test-${Env}
            - Name: API_GATEWAY_URL
              Value: !Sub test-${Env}
            - Name: API_KEY
              Value: !Sub test-${Env}
            - Name: S3_BUCKET
              Value: !Sub test-${Env}

  # # CodeDeploy Application for ECS Blue/Green Deployment
  # CodeDeployECSApplication:
  #   Type: AWS::CodeDeploy::Application
  #   Properties:
  #     ComputePlatform: ECS

  # # CodeDeploy ECS Deployment Group
  # CodeDeployECSDeploymentGroup:
  #   Type: AWS::CodeDeploy::DeploymentGroup
  #   Properties:
  #     ApplicationName: !Ref CodeDeployECSApplication
  #     DeploymentGroupName: !Sub '${Prefix}-${Env}-ecs-deployment-group'
  #     ServiceRole: !Ref Role
  #     DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
  #     BlueGreenDeploymentConfiguration:
  #       TerminateBlueInstancesOnDeploymentSuccess:
  #         Action: TERMINATE
  #         TerminationWaitTimeInMinutes: 5
  #     LoadBalancerInfo:
  #       TargetGroupInfoList:
  #         - Name: !Ref ECSLoadBalancerTargetGroup
  #     ECSService:
  #       ClusterName: !Ref ECSCluster
  #       ServiceName: !Sub '${Prefix}-${Env}-ecs-service'
